"""Command line interface for sygus-check."""

import argparse
import sys

from . import __version__, check, semantic
from .problem import Problem, SygusError
from .sexpr import ParseError
from .solution import Solution, SolutionError

EXIT_CORRECT = 0
EXIT_INCORRECT = 1
EXIT_UNKNOWN = 2
EXIT_ERROR = 3

GREEN, RED, YELLOW, BOLD, OFF = "\033[32m", "\033[31m", "\033[33m", "\033[1m", "\033[0m"


def make_parser():
    p = argparse.ArgumentParser(
        prog="sygus-check",
        description="Independently check a candidate solution to a SyGuS v2 "
                    "problem: a syntactic check that every solution term is "
                    "generated by the declared grammar, and a semantic check "
                    "that discharges the verification condition with an SMT "
                    "solver.")
    p.add_argument("solution", help="file with the solver's output: a sequence "
                                    "of define-fun commands, optionally wrapped "
                                    "in parentheses")
    p.add_argument("problem", help="the reference SyGuS v2 (.sy) file")
    p.add_argument("--solver", default="cvc5", help="SMT solver binary (default: cvc5)")
    p.add_argument("--solver-arg", action="append", default=[], metavar="ARG",
                   help="extra argument passed to the solver (repeatable)")
    p.add_argument("--logic", default=None,
                   help="logic for the verification condition (default: ALL)")
    p.add_argument("--timeout", type=float, default=None, metavar="SEC",
                   help="wall-clock limit for each solver call")
    p.add_argument("--no-syntactic", action="store_true", help="skip the grammar check")
    p.add_argument("--no-semantic", action="store_true", help="skip the SMT check")
    p.add_argument("--keep-vc", action="store_true",
                   help="keep the generated verification condition on disk, as "
                        "<solution>-vc.smt2 in the working directory")
    p.add_argument("--vc-out", metavar="FILE", default=None,
                   help="write the verification condition to FILE ('-' for "
                        "stdout) and still run the checks")
    p.add_argument("--print-vc", action="store_true",
                   help="print the verification condition and exit without "
                        "running any check")
    p.add_argument("--workdir", default=".", help="where to write temporary files")
    p.add_argument("--no-color", action="store_true")
    p.add_argument("-q", "--quiet", action="store_true",
                   help="print only the final verdict")
    p.add_argument("--version", action="version", version="sygus-check " + __version__)
    return p


def main(argv=None):
    args = make_parser().parse_args(argv)
    color = not args.no_color and sys.stdout.isatty()

    def c(code, s):
        return (code + s + OFF) if color else s

    try:
        problem = Problem.from_file(args.problem)
    except (OSError, ParseError, SygusError) as e:
        print("error: %s: %s" % (args.problem, e), file=sys.stderr)
        return EXIT_ERROR
    try:
        solution = Solution.from_file(args.solution)
    except (OSError, ParseError, SolutionError) as e:
        print("error: %s: %s" % (args.solution, e), file=sys.stderr)
        return EXIT_ERROR

    if args.print_vc:
        print(semantic.build_smt2(problem, solution, logic=args.logic))
        return EXIT_CORRECT

    if args.vc_out and args.no_semantic:
        # Nothing else would generate it, so honour the request anyway.
        smt2 = semantic.build_smt2(problem, solution, logic=args.logic)
        if args.vc_out == "-":
            print(smt2)
        else:
            with open(args.vc_out, "w") as f:
                f.write(smt2)

    try:
        report = check.run(
            problem, solution,
            do_syntactic=not args.no_syntactic,
            do_semantic=not args.no_semantic,
            solver=args.solver, solver_args=args.solver_arg, logic=args.logic,
            timeout=args.timeout, workdir=args.workdir, keep=args.keep_vc,
            vc_out=args.vc_out)
    except (SygusError, RuntimeError) as e:
        print("error: %s" % e, file=sys.stderr)
        return EXIT_ERROR

    if not args.quiet:
        _print(report, c)
    verdict = {"correct": (GREEN, "correct"),
               "incorrect": (RED, "incorrect"),
               "unknown": (YELLOW, "unknown")}[report.status]
    print(c(BOLD, "result: ") + c(verdict[0], verdict[1]))
    return {"correct": EXIT_CORRECT, "incorrect": EXIT_INCORRECT,
            "unknown": EXIT_UNKNOWN}[report.status]


def _print(report, c):
    for level, msg in report.signature:
        tag = c(RED, "[signature] ") if level == "error" else c(YELLOW, "[signature] ")
        print(tag + msg)
    for r in report.syntactic:
        mark = {"ok": (GREEN, "ok"), "no-grammar": (GREEN, "ok"),
                "violation": (RED, "violation"),
                "inconclusive": (YELLOW, "inconclusive")}[r.status]
        print(c(BOLD, "[syntactic] ") + "%s: %s" % (r.name, c(mark[0], mark[1])))
        for m in r.messages:
            print("            " + m)
    s = report.semantic
    if s is not None:
        mark = {"correct": (GREEN, "valid"), "vacuous": (GREEN, "valid (no constraints)"),
                "incorrect": (RED, "invalid"), "unknown": (YELLOW, "unknown"),
                "error": (RED, "error")}[s.status]
        print(c(BOLD, "[semantic]  ") + c(mark[0], mark[1]))
        for m in s.messages:
            print("            " + m)
