"""Semantic check: build the SMT-LIB verification condition and run a solver.

For a SyGuS problem with assumptions ``A_i`` and constraints ``C_j`` over the
universally quantified variables ``X``, a solution is correct iff

    forall X. (/\\ A_i) => (/\\ C_j)

holds after replacing every function to synthesize by its definition.  We ask
the solver for the negation,

    exists X. (/\\ A_i) /\\ (\\/ ~C_j)

so ``unsat`` means the solution is correct.
"""

import os
import subprocess

from .sexpr import SList, to_str


class SemanticResult:
    #: status is one of 'correct', 'incorrect', 'unknown', 'error', 'vacuous'
    def __init__(self, status, messages=None, smt2=None, output="", model=None):
        self.status = status
        self.messages = messages or []
        self.smt2 = smt2
        self.output = output
        self.model = model

    @property
    def ok(self):
        return self.status in ("correct", "vacuous")


def build_smt2(problem, solution, logic=None, get_model=False):
    """Return the SMT-LIB script encoding the negated verification condition."""
    goals, extra_vars = problem.expanded_constraints()
    out = []
    out.append("; verification condition generated by sygus-check")
    if problem.source:
        out.append("; problem:  %s" % problem.source)
    if solution.source:
        out.append("; solution: %s" % solution.source)
    out.append("(set-logic %s)" % (logic or "ALL"))
    if get_model:
        out.append("(set-option :produce-models true)")
    if problem.preamble:
        out.append("")
        out.append("; --- definitions from the SyGuS problem ---")
        out.extend(to_str(c) for c in problem.preamble)
    out.append("")
    out.append("; --- candidate solution ---")
    for d in solution.defs:
        out.append(str(d))
    if problem.variables or extra_vars:
        out.append("")
        out.append("; --- universal variables ---")
        for n, s in list(problem.variables) + extra_vars:
            out.append("(declare-const %s %s)" % (n, to_str(s)))
    if problem.assumptions:
        out.append("")
        out.append("; --- assumptions ---")
        for a in problem.assumptions:
            out.append("(assert %s)" % to_str(a))
    out.append("")
    out.append("; --- negation of the constraints ---")
    if len(goals) == 1:
        out.append("(assert (not %s))" % to_str(goals[0]))
    else:
        out.append("(assert (or")
        for g in goals:
            out.append("  (not %s)" % to_str(g))
        out.append("))")
    out.append("(check-sat)")
    if get_model:
        out.append("(get-model)")
    out.append("")
    return "\n".join(out)


def run_solver(smt2_path, solver="cvc5", args=(), timeout=None):
    cmd = [solver] + list(args) + [smt2_path]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except FileNotFoundError:
        raise RuntimeError("solver not found: %s" % solver)
    except subprocess.TimeoutExpired:
        return None, "timeout after %ss" % timeout
    return proc, (proc.stdout or "") + (proc.stderr or "")


def check(problem, solution, solver="cvc5", solver_args=(), logic=None,
          timeout=None, workdir=".", keep=False):
    """Run the semantic check.  Returns a :class:`SemanticResult`."""
    goals, _ = problem.expanded_constraints()
    if not goals:
        return SemanticResult("vacuous",
                              ["the problem has no constraints; any well-sorted "
                               "solution is correct"])
    smt2 = build_smt2(problem, solution, logic=logic)
    path = os.path.join(workdir, "sygus-check-vc.smt2")
    with open(path, "w") as f:
        f.write(smt2)
    proc, output = run_solver(path, solver, solver_args, timeout)
    msgs = ["verification condition: %s" % path] if keep else []
    if proc is None:
        return SemanticResult("unknown", msgs + [output], smt2, output)
    answer = _answer(output)
    if answer == "unsat":
        status = "correct"
        msgs.append("solver reports unsat: the constraints are entailed")
    elif answer == "sat":
        status = "incorrect"
        msgs.append("solver reports sat: the constraints can be falsified")
    else:
        status = "unknown" if answer == "unknown" else "error"
        msgs.append("solver did not decide the verification condition")
        msgs.append(output.strip())
    model = None
    if status == "incorrect":
        model = _counterexample(problem, solution, solver, solver_args, logic,
                                timeout, workdir)
        if model:
            msgs.append("counterexample:")
            msgs.extend("  " + l for l in model.splitlines() if l.strip())
    if not keep:
        try:
            os.remove(path)
        except OSError:
            pass
    return SemanticResult(status, msgs, smt2, output, model)


def _answer(output):
    for line in output.splitlines():
        line = line.strip()
        if line in ("sat", "unsat", "unknown"):
            return line
    return None


def _counterexample(problem, solution, solver, solver_args, logic, timeout,
                    workdir):
    smt2 = build_smt2(problem, solution, logic=logic, get_model=True)
    path = os.path.join(workdir, "sygus-check-cex.smt2")
    with open(path, "w") as f:
        f.write(smt2)
    try:
        proc, output = run_solver(path, solver, solver_args, timeout)
    except RuntimeError:
        return None
    finally:
        try:
            os.remove(path)
        except OSError:
            pass
    if proc is None:
        return None
    lines = output.splitlines()
    for i, l in enumerate(lines):
        if l.strip() == "sat":
            return "\n".join(lines[i + 1:]).strip()
    return None
