"""Syntactic check: is a solution term generated by the declared grammar?

For a term ``t`` we compute, bottom-up, the set of nonterminals that derive
``t``.  Recursion is well founded because the only way a rule keeps the term
unchanged is a chain rule ``A -> B``; those are resolved by iterating to a
fixed point on the set for that single term.
"""

from .sexpr import SList, to_str
from .terms import expand_lets, key, literal_sorts, strip_annotations, substitute


class GrammarUnsupported(Exception):
    """Raised for grammar features this checker does not model."""


class SyntacticResult:
    #: status is one of 'ok', 'violation', 'no-grammar', 'inconclusive'
    def __init__(self, name, status, messages=None):
        self.name = name
        self.status = status
        self.messages = messages or []

    @property
    def ok(self):
        return self.status in ("ok", "no-grammar")


class Deriver:
    def __init__(self, grammar, sortenv, variables):
        self.g = grammar
        self.sorts = sortenv
        self.vars = {n: sortenv.canon(s) for n, s in variables}
        self.nt_set = set(grammar.nts)
        self.memo = {}

    # -- public ----------------------------------------------------------
    def derives(self, term, nt):
        return nt in self.nts_of(term)

    def nts_of(self, term):
        """Set of nonterminals deriving *term*."""
        k = key(term)
        cached = self.memo.get(k)
        if cached is not None:
            return cached
        # Children first: every non-chain rule strictly decreases term size.
        if isinstance(term, list):
            for child in term:
                self.nts_of(child)
        acc = set()
        changed = True
        while changed:
            changed = False
            for nt in self.g.nts:
                if nt in acc:
                    continue
                for rule in self.g.rules[nt]:
                    if self._match(term, rule, acc):
                        acc.add(nt)
                        changed = True
                        break
        self.memo[k] = acc
        return acc

    # -- matching --------------------------------------------------------
    def _match(self, term, rule, same_term_nts):
        """Does *term* match grammar term *rule*?

        *same_term_nts* is the set of nonterminals already known to derive
        *term* itself, used for chain rules.
        """
        if not isinstance(rule, list):
            if rule in self.nt_set:
                return rule in same_term_nts
            return not isinstance(term, list) and term == rule
        if not rule:
            raise GrammarUnsupported("empty grammar term")
        head = rule[0]
        if head == "Constant" and len(rule) == 2:
            return self._is_constant(term, rule[1])
        if head == "Variable" and len(rule) == 2:
            return self._is_variable(term, rule[1])
        if head == "let":
            raise GrammarUnsupported("'let' in a grammar production")
        if head == "!":
            return self._match(term, rule[1], same_term_nts)
        if head == "_":  # indexed identifier used as a nullary term
            return isinstance(term, list) and to_str(term) == to_str(rule)
        # Application: (Identifier GTerm+)
        if not isinstance(term, list) or len(term) != len(rule):
            return False
        if not self._same_head(term[0], head):
            return False
        return all(self._match_sub(t, r) for t, r in zip(term[1:], rule[1:]))

    def _match_sub(self, term, rule):
        """Match a proper subterm, whose nonterminal sets are already known."""
        if not isinstance(rule, list) and rule in self.nt_set:
            return rule in self.nts_of(term)
        return self._match(term, rule, self.nts_of(term))

    @staticmethod
    def _same_head(th, rh):
        if isinstance(th, list) or isinstance(rh, list):
            return to_str(th) == to_str(rh)
        return th == rh

    def _is_constant(self, term, sort):
        ls = literal_sorts(term)
        if ls is None:
            return False
        want = self.sorts.canon(sort)
        return any(self.sorts.canon(s) == want for s in ls)

    def _is_variable(self, term, sort):
        if isinstance(term, list):
            return False
        s = self.vars.get(term)
        return s is not None and s == self.sorts.canon(sort)


def rename_args(defn, synth_fun):
    """Rewrite *defn*'s body to use the parameter names of *synth_fun*."""
    sub = {}
    for (dname, _), (sname, _) in zip(defn.args, synth_fun.args):
        if dname != sname:
            sub[dname] = sname
    return substitute(defn.body, sub) if sub else defn.body


def check(synth_fun, defn, sortenv):
    """Check that *defn*'s body is generated by *synth_fun*'s grammar."""
    name = synth_fun.name
    if synth_fun.grammar is None:
        return SyntacticResult(name, "no-grammar",
                               ["no grammar declared: any well-sorted term is "
                                "allowed, nothing to check"])
    body = strip_annotations(expand_lets(rename_args(defn, synth_fun)))
    d = Deriver(synth_fun.grammar, sortenv, synth_fun.args)
    try:
        derived = d.nts_of(body)
    except GrammarUnsupported as e:
        return SyntacticResult(name, "inconclusive",
                               ["cannot check this grammar: %s" % e])
    start = synth_fun.grammar.start
    if start in derived:
        return SyntacticResult(name, "ok",
                               ["term is derivable from start symbol %s" % start])
    msgs = []
    if derived:
        msgs.append("term is derivable from %s but not from the start symbol %s"
                    % (", ".join(sorted(derived)), start))
    else:
        msgs.append("term is not derivable from any nonterminal "
                    "(start symbol is %s)" % start)
    msgs.extend(_diagnose(d, body))
    return SyntacticResult(name, "violation", msgs)


def _diagnose(d, term, depth=0, out=None):
    """Point at the deepest subterms that no nonterminal derives."""
    if out is None:
        out = []
    if d.nts_of(term):
        return out
    culprits = [c for c in term[1:]] if isinstance(term, list) else []
    bad = [c for c in culprits if not d.nts_of(c)]
    if bad:
        for c in bad:
            _diagnose(d, c, depth + 1, out)
    else:
        s = to_str(term)
        if len(s) > 120:
            s = s[:117] + "..."
        out.append("  no production generates: %s" % s)
    return out
